# Generated by Django 4.1.6 on 2023-03-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcpt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Mssg',
        ),
        migrations.RenameField(
            model_name='add_blog',
            old_name='title',
            new_name='tit',
        ),
    ]
